// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwjntpzooiubymdzzwvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3am50cHpvb2l1YnltZHp6d3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDEzMjYsImV4cCI6MjA2NzkxNzMyNn0.Nxeu__rZ8kylVtHktLFeRUTFlCJOIVxAoNYRwmdG_KM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
